### ISSUE TITLE
Help with hosting the masterlist file.

### ISSUE THREAD

**Issue by nickdodd25** [spmn/sa-mp_masterlist_fix#1]
I just ran across this and seen you were interested in some help hosting the masterlist file. I added it to my hosted tab monitor, the file location can be found here 

https://monitor.teamshrimp.com/list/masterlist.txt

Its behind cloudflare and my vps has plenty of bandwidth so there should be no issues if this would start getting heavily used, and it should be pretty fast for about everyone.

I also changed the fetch times to 15 minutes, and i also slowed the crawling down to 1 page per second, it takes a bit longer to fetch but it is nicer on sacnr monitors webserver.

**Comment by spmn** [comment]
Thank you for your support!

I've managed to bypass the browser ban by using a real user agent, but CF is trying to redirect all HTTP requests to HTTPS... unfortunately SA-MP client has no idea about SSL certificates. My knowledge in reverse engineering is not high enough to address this problem.

I have no past experiences with CF, but from what I've seen on Google it seems that you can disable SSL for subdomains. Can you try that?

**Comment by nickdodd25** [comment]
I have now disabled browser integrity check and made https optional for anything in the /list folder. Everything should work now.

**Comment by spmn** [comment]
Masterlist fix is now using your server by default.

> I also changed the fetch times to 15 minutes, and i also slowed the crawling down to 1 page per second, it takes a bit longer to fetch but it is nicer on sacnr monitors webserver.

It seems that SACNR adds and removes servers from their masterlist once at ~12 hours. You should change fetch times back to 12 hours so you won't generate useless traffic.

**Comment by nickdodd25** [comment]
Sorry for the delayed response, i've been sick for the past few days. 

I changed the time back to 6 hours, in the logs the server totals seem to change around 3ish hours. I will keep an eye on it and adjust it as it is needed.

Also i was thinking, would it be better for the smaller servers if the ip orders were shuffled around before they are saved? In the client it shows all servers ordered by players just as they are on sacnr monitor.

**Comment by spmn** [comment]
That's a good idea! You can change the order servers are shown on SA-MP client as long as you don't promote certain servers.

**Comment by nickdodd25** [comment]
The list of ips are not randomized. I made a pull request with the changes.

**Comment by spmn** [comment]
Merged.

Thanks for your contribution!
