### ISSUE TITLE
Banned from SACNR masterlist! :O (only SA-MP User Agent tho)

### ISSUE THREAD

**Issue by Chaprnks** [spmn/sa-mp_masterlist_fix#5]
![jjnp5w](https://cloud.githubusercontent.com/assets/6340970/17916074/ed5f03a4-697d-11e6-934d-0102485a22d5.png)

**Comment by spmn** [comment]
This issue has already been reported.
I'm waiting for a response from SACNR.

**Comment by spmn** [comment]
Fixed
