### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Chaprnks** [spmn/sa-mp_masterlist_fix#6]
Internet tab shows nothing anymore, hopefully its not the same issue as last time (overbearing cloudflare detecting it as network attack or something).

**Comment by spmn** [comment]
[Works fine here.](http://prntscr.com/ipsu83)
Can you confirm that you are using SA-MP 0.3.7 **R1** browser?

**Comment by uBlock-user** [comment]
loads only 685 servers on my end while the interlist list has 4K servers. What changed ?

**Comment by spmn** [comment]
What version of the SA-MP browser are you using?

Edit: SACNR reports roughly 700 servers back atm, so my guess is that everything works just fine.

**Comment by uBlock-user** [comment]
0.3.7 r1

**Comment by uBlock-user** [comment]
> SACNR reports roughly 700 servers back atm

ofcourse, it will only show 600-700 since it's the source, i see.
